server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 入驻地址
  instance:
    instance-id: orderFeign80
    prefer-ip-address: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间,也就是feign处理请求的超时时间
  ReadTimeout: 6000
  # 指的是feign建立连接所用的超时时间
  ConnectTimeout: 4000
  eureka:
    enabled: true

logging:
  level:
    # Feign提供了日志打印功能，我们可以通过配置来调整日恙级别，从而了解Feign 中 Http请求的细节。说白了就是对Feign接口的调用情况进行监控和输出
    com.atguigu.springcloud.service.PaymentFeignService: debug

